/*
 * Edgecore 5GC
 *
 * Edgecore 5GC API server.  You can find out more about Edgecore 5GC at [http://5gc.edge-core.cn](http://5gc.edge-core.cn).
 *
 * API version: 1.0.0
 * Contact: jimmy_ou@edge-core.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
)

// AuthLoginPost - Authentication login
func AuthLoginPost(c *gin.Context) {

	var loginData LoginData
	if err := c.ShouldBindJSON(&loginData); err != nil {
		panic(err)
	}
	fmt.Printf("Got username: %v, password: %v from request\n", loginData.Username, loginData.Password)

	for _, v := range UserDB {
		if loginData.Username == v.Username && loginData.Password == v.Password {
			c.JSON(http.StatusOK, gin.H{})
			return
		}
	}
	c.JSON(http.StatusForbidden, gin.H{})
}
