/*
 * Edgecore 5GC
 *
 * Edgecore 5GC API server.  You can find out more about Edgecore 5GC at [http://5gc.edge-core.cn](http://5gc.edge-core.cn).
 *
 * API version: 1.0.0
 * Contact: jimmy_ou@edge-core.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// SubscriberDelUeIdServingPlmnIdDelete - Deletes a subscriber
func SubscriberDelUeIdServingPlmnIdDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// SubscriberGet - Get subscribers list
func SubscriberGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// SubscriberUeIdServingPlmnIdGet - Get specific subscribe context
func SubscriberUeIdServingPlmnIdGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// SubscriberUeIdServingPlmnIdPost - Add/Update subscribe
func SubscriberUeIdServingPlmnIdPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
