/*
 * Edgecore 5GC
 *
 * Edgecore 5GC API server.  You can find out more about Edgecore 5GC at [http://5gc.edge-core.cn](http://5gc.edge-core.cn).
 *
 * API version: 1.0.0
 * Contact: jimmy_ou@edge-core.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
)

// RanGet - Get all RAN
func RanGet(c *gin.Context) {
	c.JSON(http.StatusOK, RANs)
}

// RanGNbIdGet - Get specific RAN
func RanGNbIdGet(c *gin.Context) {
	gNBId:=c.Param("gNbId")
	fmt.Printf("Got gNbId:%v\n",gNBId)

	for _, v := range RANs {
		if v.RanId.GNbId.GNBValue == gNBId {
			c.JSON(http.StatusOK, v)
			return
		}
	}
	c.JSON(http.StatusNotFound, gin.H{})
}
