/*
 * Edgecore 5GC
 *
 * Edgecore 5GC API server.  You can find out more about Edgecore 5GC at [http://5gc.edge-core.cn](http://5gc.edge-core.cn). 
 *
 * API version: 1.0.0
 * Contact: jimmy_ou@edge-core.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Rotations struct {

	R1 string `json:"r1"`

	R2 string `json:"r2"`

	R3 string `json:"r3"`

	R4 string `json:"r4"`

	R5 string `json:"r5"`
}
