/*
 * Edgecore 5GC
 *
 * Edgecore 5GC API server.  You can find out more about Edgecore 5GC at [http://5gc.edge-core.cn](http://5gc.edge-core.cn). 
 *
 * API version: 1.0.0
 * Contact: jimmy_ou@edge-core.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SharedData2 struct {

	SharedDataId string `json:"sharedDataId"`

	SharedAmData AccessAndMobilitySubscriptionData `json:"sharedAmData,omitempty"`

	SharedSmsSubsData SmsSubscriptionData `json:"sharedSmsSubsData,omitempty"`

	SharedSmsMngSubsData SmsManagementSubscriptionData `json:"sharedSmsMngSubsData,omitempty"`

	SharedDnnConfigurations map[string]DnnConfiguration `json:"sharedDnnConfigurations,omitempty"`

	SharedTraceData *TraceData2 `json:"sharedTraceData,omitempty"`

	SharedSnssaiInfos map[string]SnssaiInfo `json:"sharedSnssaiInfos,omitempty"`

	SharedAuthenticationSubscription SharedAuthenticationSubscription2 `json:"sharedAuthenticationSubscription,omitempty"`
}
