/*
 * Edgecore 5GC
 *
 * Edgecore 5GC API server.  You can find out more about Edgecore 5GC at [http://5gc.edge-core.cn](http://5gc.edge-core.cn). 
 *
 * API version: 1.0.0
 * Contact: jimmy_ou@edge-core.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RatType string

// List of RatType
const (
	NR RatType = "NR"
	EUTRA RatType = "EUTRA"
	WLAN RatType = "WLAN"
	VIRTUAL RatType = "VIRTUAL"
)
