/*
 * Edgecore 5GC
 *
 * Edgecore 5GC API server.  You can find out more about Edgecore 5GC at [http://5gc.edge-core.cn](http://5gc.edge-core.cn). 
 *
 * API version: 1.0.0
 * Contact: jimmy_ou@edge-core.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AccessAndMobilitySubscriptionData struct {

	SupportedFeatures string `json:"supportedFeatures,omitempty"`

	Gpsis []string `json:"gpsis,omitempty"`

	InternalGroupIds []string `json:"internalGroupIds,omitempty"`

	SubscribedUeAmbr *AmbrRm `json:"subscribedUeAmbr,omitempty"`

	Nssai *Nssai `json:"nssai,omitempty"`

	RatRestrictions []RatType `json:"ratRestrictions,omitempty"`

	ForbiddenAreas []Area `json:"forbiddenAreas,omitempty"`

	ServiceAreaRestriction ServiceAreaRestriction `json:"serviceAreaRestriction,omitempty"`

	CoreNetworkTypeRestrictions []CoreNetworkType `json:"coreNetworkTypeRestrictions,omitempty"`

	RfspIndex *int32 `json:"rfspIndex,omitempty"`

	SubsRegTimer *int32 `json:"subsRegTimer,omitempty"`

	UeUsageType int32 `json:"ueUsageType,omitempty"`

	MpsPriority bool `json:"mpsPriority,omitempty"`

	McsPriority bool `json:"mcsPriority,omitempty"`

	ActiveTime *int32 `json:"activeTime,omitempty"`

	DlPacketCount int32 `json:"dlPacketCount,omitempty"`

	SorInfo SorInfo `json:"sorInfo,omitempty"`

	MicoAllowed bool `json:"micoAllowed,omitempty"`

	SharedAmDataIds []string `json:"sharedAmDataIds,omitempty"`

	OdbPacketServices OdbPacketServices `json:"odbPacketServices,omitempty"`
}
