/*
 * Edgecore 5GC
 *
 * Edgecore 5GC API server.  You can find out more about Edgecore 5GC at [http://5gc.edge-core.cn](http://5gc.edge-core.cn). 
 *
 * API version: 1.0.0
 * Contact: jimmy_ou@edge-core.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SubsData struct {

	PlmnId int32 `json:"plmnId,omitempty"`

	UeId string `json:"ueId,omitempty"`

	AuthenticationSubscription AuthenticationSubscription `json:"authenticationSubscription,omitempty"`

	AccessAndMobilitySubscriptionData AccessAndMobilitySubscriptionData `json:"accessAndMobilitySubscriptionData,omitempty"`

	SessionManagementSubscriptionData SessionManagementSubscriptionData `json:"sessionManagementSubscriptionData,omitempty"`

	SmfSelectionSubscriptionData SmfSelectionSubscriptionData `json:"smfSelectionSubscriptionData,omitempty"`

	AmPolicyData AmPolicyData `json:"amPolicyData,omitempty"`

	SmPolicyData SmPolicyData `json:"smPolicyData,omitempty"`
}
