/*
 * Edgecore 5GC
 *
 * Edgecore 5GC API server.  You can find out more about Edgecore 5GC at [http://5gc.edge-core.cn](http://5gc.edge-core.cn). 
 *
 * API version: 1.0.0
 * Contact: jimmy_ou@edge-core.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SessionRule struct {

	AuthSessAmbr Ambr2 `json:"authSessAmbr,omitempty"`

	AuthDefQos AuthorizedDefaultQos `json:"authDefQos,omitempty"`

	// Univocally identifies the session rule within a PDU session.
	SessRuleId string `json:"sessRuleId"`

	// A reference to UsageMonitoringData policy decision type. It is the umId described in subclause 5.6.2.12.
	RefUmData *string `json:"refUmData,omitempty"`

	// A reference to UsageMonitoringData policy decision type to apply for Non-3GPP access. It is the umId described in subclause 5.6.2.12.
	RefUmN3gData *string `json:"refUmN3gData,omitempty"`

	// A reference to the condition data. It is the condId described in subclause 5.6.2.9.
	RefCondData *string `json:"refCondData,omitempty"`
}
