/*
 * Edgecore 5GC
 *
 * Edgecore 5GC API server.  You can find out more about Edgecore 5GC at [http://5gc.edge-core.cn](http://5gc.edge-core.cn). 
 *
 * API version: 1.0.0
 * Contact: jimmy_ou@edge-core.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SmPolicyDnnData - Contains the SM policy data for a given DNN (and S-NSSAI).
type SmPolicyDnnData struct {

	Dnn string `json:"dnn"`

	AllowedServices []string `json:"allowedServices,omitempty"`

	SubscCats []string `json:"subscCats,omitempty"`

	GbrUl string `json:"gbrUl,omitempty"`

	GbrDl string `json:"gbrDl,omitempty"`

	AdcSupport bool `json:"adcSupport,omitempty"`

	SubscSpendingLimits bool `json:"subscSpendingLimits,omitempty"`

	Ipv4Index int32 `json:"ipv4Index,omitempty"`

	Ipv6Index int32 `json:"ipv6Index,omitempty"`

	Offline bool `json:"offline,omitempty"`

	Online bool `json:"online,omitempty"`

	ChfInfo ChargingInformation `json:"chfInfo,omitempty"`

	RefUmDataLimitIds map[string]LimitIdToMonitoringKey `json:"refUmDataLimitIds,omitempty"`

	MpsPriority bool `json:"mpsPriority,omitempty"`

	ImsSignallingPrio bool `json:"imsSignallingPrio,omitempty"`

	MpsPriorityLevel int32 `json:"mpsPriorityLevel,omitempty"`
}
