/*
 * Edgecore 5GC
 *
 * Edgecore 5GC API server.  You can find out more about Edgecore 5GC at [http://5gc.edge-core.cn](http://5gc.edge-core.cn). 
 *
 * API version: 1.0.0
 * Contact: jimmy_ou@edge-core.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// TimePeriod - Contains the periodicity for the defined usage monitoring data limits.
type TimePeriod struct {

	Period Periodicity `json:"period"`

	MaxNumPeriod int32 `json:"maxNumPeriod,omitempty"`
}
