/*
 * Edgecore 5GC
 *
 * Edgecore 5GC API server.  You can find out more about Edgecore 5GC at [http://5gc.edge-core.cn](http://5gc.edge-core.cn). 
 *
 * API version: 1.0.0
 * Contact: jimmy_ou@edge-core.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UeContext struct {

	AccessType string `json:"accessType,omitempty"`

	Supi string `json:"supi,omitempty"`

	Guti string `json:"guti,omitempty"`

	Mcc string `json:"mcc,omitempty"`

	Mnc string `json:"mnc,omitempty"`

	Tac string `json:"tac,omitempty"`

	PduSessions []UeContextPduSessions `json:"pduSessions,omitempty"`

	CmState string `json:"cmState,omitempty"`
}
