/*
 * Edgecore 5GC
 *
 * Edgecore 5GC API server.  You can find out more about Edgecore 5GC at [http://5gc.edge-core.cn](http://5gc.edge-core.cn). 
 *
 * API version: 1.0.0
 * Contact: jimmy_ou@edge-core.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ChargingInformation struct {

	// string providing an URI formatted according to IETF RFC 3986.
	PrimaryChfAddress string `json:"primaryChfAddress"`

	// string providing an URI formatted according to IETF RFC 3986.
	SecondaryChfAddress string `json:"secondaryChfAddress"`
}
