/*
 * Edgecore 5GC
 *
 * Edgecore 5GC API server.  You can find out more about Edgecore 5GC at [http://5gc.edge-core.cn](http://5gc.edge-core.cn). 
 *
 * API version: 1.0.0
 * Contact: jimmy_ou@edge-core.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TraceDepth2 string

// List of TraceDepth2
const (
	MINIMUM TraceDepth2 = "MINIMUM"
	MEDIUM TraceDepth2 = "MEDIUM"
	MAXIMUM TraceDepth2 = "MAXIMUM"
	MINIMUM_WO_VENDOR_EXTENSION TraceDepth2 = "MINIMUM_WO_VENDOR_EXTENSION"
	MEDIUM_WO_VENDOR_EXTENSION TraceDepth2 = "MEDIUM_WO_VENDOR_EXTENSION"
	MAXIMUM_WO_VENDOR_EXTENSION TraceDepth2 = "MAXIMUM_WO_VENDOR_EXTENSION"
)
