/*
 * Edgecore 5GC
 *
 * Edgecore 5GC API server.  You can find out more about Edgecore 5GC at [http://5gc.edge-core.cn](http://5gc.edge-core.cn). 
 *
 * API version: 1.0.0
 * Contact: jimmy_ou@edge-core.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Arp2 struct {

	// nullable true shall not be used for this attribute
	PriorityLevel *int32 `json:"priorityLevel"`

	PreemptCap PreemptionCapability2 `json:"preemptCap"`

	PreemptVuln PreemptionVulnerability2 `json:"preemptVuln"`
}
