/*
 * Edgecore 5GC
 *
 * Edgecore 5GC API server.  You can find out more about Edgecore 5GC at [http://5gc.edge-core.cn](http://5gc.edge-core.cn). 
 *
 * API version: 1.0.0
 * Contact: jimmy_ou@edge-core.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Constants struct {

	C1 string `json:"c1"`

	C2 string `json:"c2"`

	C3 string `json:"c3"`

	C4 string `json:"c4"`

	C5 string `json:"c5"`
}
