/*
 * Edgecore 5GC
 *
 * Edgecore 5GC API server.  You can find out more about Edgecore 5GC at [http://5gc.edge-core.cn](http://5gc.edge-core.cn). 
 *
 * API version: 1.0.0
 * Contact: jimmy_ou@edge-core.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SmfSelectionSubscriptionData struct {

	SupportedFeatures string `json:"supportedFeatures,omitempty"`

	SubscribedSnssaiInfos map[string]SnssaiInfo `json:"subscribedSnssaiInfos,omitempty"`

	SharedSnssaiInfosId string `json:"sharedSnssaiInfosId,omitempty"`
}
