/*
 * Edgecore 5GC
 *
 * Edgecore 5GC API server.  You can find out more about Edgecore 5GC at [http://5gc.edge-core.cn](http://5gc.edge-core.cn). 
 *
 * API version: 1.0.0
 * Contact: jimmy_ou@edge-core.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AuthenticationSubscription struct {

	AuthenticationMethod AuthMethod `json:"authenticationMethod"`

	PermanentKey PermanentKey `json:"permanentKey"`

	SequenceNumber string `json:"sequenceNumber"`

	AuthenticationManagementField string `json:"authenticationManagementField,omitempty"`

	VectorAlgorithm VectorAlgorithm `json:"vectorAlgorithm,omitempty"`

	Milenage Milenage `json:"milenage,omitempty"`

	Tuak Tuak `json:"tuak,omitempty"`

	Opc Opc `json:"opc,omitempty"`

	Topc Topc `json:"topc,omitempty"`

	SharedAuthenticationSubscriptionId SharedData2 `json:"sharedAuthenticationSubscriptionId,omitempty"`
}
