/*
 * Edgecore 5GC
 *
 * Edgecore 5GC API server.  You can find out more about Edgecore 5GC at [http://5gc.edge-core.cn](http://5gc.edge-core.cn). 
 *
 * API version: 1.0.0
 * Contact: jimmy_ou@edge-core.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AuthMethod string

// List of AuthMethod
const (
	_5_G_AKA AuthMethod = "5G_AKA"
	EAP_AKA_PRIME AuthMethod = "EAP_AKA_PRIME"
)
